import { BackToTop } from "@/app/components/layout/BackToTop";
import { Footer } from "@/app/components/layout/Footer";
import { Header } from "@/app/components/layout/Header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/providers/auth-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import "@/app/(main)/main.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable}  h-full antialiased`}
      data-scroll-behavior="smooth"
    >
      <TooltipProvider>
        <body className="min-h-full bg-background text-foreground font-sans">
          <AuthProvider>
            <div id="top"></div>
            <Header />
            <main>{children}</main>
            <Footer />
            <BackToTop />
          </AuthProvider>
        </body>
      </TooltipProvider>
    </html>
  );
}
