import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/components/layout/Header";
import { Footer } from "@/app/components/layout/Footer";
import { BackToTop } from "@/app/components/layout/BackToTop";
import { AuthProvider } from "@/providers/auth-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} text-foreground bg-background font-sans h-full antialiased`}
      data-scroll-behavior="smooth"
    >
      <body className="min-h-full">
        <AuthProvider>
          <div id="top"></div>
          <Header />
          <main className="">{children}</main>
          <Footer />
          <BackToTop />
        </AuthProvider>
      </body>
    </html>
  );
}
